# -*- coding: utf-8 -*-
"""for_dictation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5qSOZt1qzKb4XnHACCt53WtkMosfrwU
"""

import random
#元英文読み込み#
#pre_snt = open("/content/drive/MyDrive/for_read.txt",encoding="utf-8")
pre_snt = input("問題にしたい英文をコピペしてください")
#snt = pre_snt.read()
snt_li = pre_snt.split()

#問題数決定#
replace_number = input(str(len(snt_li))+"以下で好きな整数を入力してください")
if int(replace_number) > len(snt_li):
   replace_number=input("指定した数が大きすぎます、"+str(len(snt_li))+"以下で好きな整数を入力してください")
   while int(replace_number) > len(snt_li):
     replace_number=input("指定した数が大きすぎます、"+str(len(snt_li))+"以下で好きな整数を入力してください")
     if int(replace_number) <= len(snt_li):
        random_index = sorted(random.sample(range(len(snt_li)),int(replace_number)))
else:
  random_index = sorted(random.sample(range(len(snt_li)),int(replace_number)))

#回答作成#
question_number = 0
answer_li=[]
for answer_number in random_index :
  question_number += 1
  answer_li.append(str(question_number) + ": " + snt_li[answer_number])
answer= "\n".join(answer_li)
with open("/content/drive/MyDrive/answer.txt","w",encoding = "utf_8") as f :
  f.write(answer)

#問題文作成#
question_number = 0
for space in random_index:
  question_number += 1
  snt_li[space] =  str(question_number) + ".(     )"
examination_sentence= " ".join(snt_li)
with open("/content/drive/MyDrive/question.txt","w",encoding = "utf_8") as f :
  f.write(examination_sentence)

print("問題作成が完了しました。question.txtを開き、音声を聞いて問題を解いてください。\n回答後はanswer.txtを確認し、答え合わせを行ってください\n問題を解き終わるまではこのプログラムを再度実行しないでください")